# Generated by Django 6.1.1 on 2026-10-02 13:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FormaPagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX')], max_length=10)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ValorRecebido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Troco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('CriadaEm', models.DateTimeField(auto_now_add=True)),
                ('Proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='VendasRealizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'venda',
                'verbose_name_plural': 'vendas',
                'ordering': ['-CriadaEm'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeProduto', models.CharField(max_length=120)),
                ('UnidadeVenda', models.CharField(max_length=12)),
                ('Quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('PrecoUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ItensVendidos', to='produtos.produto')),
                ('Venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Itens', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'item da venda',
                'verbose_name_plural': 'itens da venda',
                'ordering': ['id'],
            },
        ),
    ]
