# Generated by Django 6.1.1 on 2026-10-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='NomeCliente',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
