# Generated by Django 6.1.1 on 2026-10-02 19:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def PreencherCustoHistorico(Apps, SchemaEditor):
    ItemVenda = Apps.get_model("vendas", "ItemVenda")
    ItemVenda.objects.update(CustoUnitario=models.F("PrecoUnitario"))


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_venda_nomecliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='CustoUnitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='Lucro',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='venda',
            name='Lucro',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.RunPython(
            PreencherCustoHistorico,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='ResumoVendaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ano', models.PositiveSmallIntegerField()),
                ('Mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('QuantidadeVendas', models.PositiveIntegerField(default=0)),
                ('TotalVendido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('Lucro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('Proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ResumosVendasMensais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'resumo mensal de vendas',
                'verbose_name_plural': 'resumos mensais de vendas',
                'ordering': ['-Ano', '-Mes'],
                'constraints': [models.UniqueConstraint(fields=('Proprietario', 'Ano', 'Mes'), name='ResumoVendaMensalUnico')],
            },
        ),
    ]
