# Generated by Django 6.1.1 on 2026-10-05 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_loteestoque'),
        ('vendas', '0003_itemvenda_custounitario_itemvenda_lucro_venda_lucro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='Lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ItensVendidos', to='produtos.loteestoque'),
        ),
    ]
