# Generated by Django 6.1.1 on 2026-10-08 17:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_itemvenda_lote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='FormaPagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('conta_cliente', 'Conta do cliente')], max_length=20),
        ),
        migrations.CreateModel(
            name='ContaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeCliente', models.CharField(max_length=80)),
                ('Ativa', models.BooleanField(default=True)),
                ('CriadaEm', models.DateTimeField(auto_now_add=True)),
                ('AtualizadaEm', models.DateTimeField(auto_now=True)),
                ('Proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ContinhasClientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'continha de cliente',
                'verbose_name_plural': 'continhas de clientes',
                'ordering': ['NomeCliente'],
            },
        ),
        migrations.AddField(
            model_name='venda',
            name='ContaCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Vendas', to='vendas.contacliente'),
        ),
        migrations.CreateModel(
            name='LancamentoContaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(choices=[('compra', 'Compra'), ('pagamento', 'Pagamento')], max_length=12)),
                ('Descricao', models.CharField(blank=True, max_length=140)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('CriadoEm', models.DateTimeField(auto_now_add=True)),
                ('Conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lancamentos', to='vendas.contacliente')),
                ('Venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LancamentosConta', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'lançamento de continha',
                'verbose_name_plural': 'lançamentos de continhas',
                'ordering': ['-CriadoEm', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RegistroVendaAntiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VendaOriginalId', models.PositiveIntegerField()),
                ('NomeCliente', models.CharField(blank=True, max_length=80)),
                ('FormaPagamento', models.CharField(max_length=20)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Lucro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ValorRecebido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Troco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('CriadaEm', models.DateTimeField()),
                ('ConsolidadaEm', models.DateTimeField(auto_now_add=True)),
                ('Proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RegistrosVendasAntigas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de venda antiga',
                'verbose_name_plural': 'registros de vendas antigas',
                'ordering': ['-CriadaEm'],
            },
        ),
        migrations.CreateModel(
            name='ItemRegistroVendaAntiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeProduto', models.CharField(max_length=120)),
                ('UnidadeVenda', models.CharField(max_length=12)),
                ('Quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('PrecoUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Itens', to='vendas.registrovendaantiga')),
            ],
            options={
                'verbose_name': 'item de venda antiga',
                'verbose_name_plural': 'itens de vendas antigas',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='contacliente',
            constraint=models.UniqueConstraint(fields=('Proprietario', 'NomeCliente'), name='ContaClienteUnicaPorProprietario'),
        ),
        migrations.AddConstraint(
            model_name='registrovendaantiga',
            constraint=models.UniqueConstraint(fields=('Proprietario', 'VendaOriginalId'), name='RegistroVendaAntigaUnico'),
        ),
    ]
