# Generated by Django 6.1.1 on 2026-10-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=120, unique=True)),
                ('Telefone', models.CharField(blank=True, max_length=20)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Cidade', models.CharField(blank=True, max_length=80)),
                ('Ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ['Nome'],
            },
        ),
    ]
