# Generated by Django 6.1.1 on 2026-10-02 13:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=120, unique=True)),
                ('Categoria', models.CharField(blank=True, max_length=80)),
                ('UnidadeVenda', models.CharField(choices=[('unidade', 'Unidade'), ('quilograma', 'Quilograma')], default='unidade', max_length=12)),
                ('QuantidadeEstoque', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('EstoqueMinimo', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('PrecoVenda', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('Ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['Nome'],
            },
        ),
    ]
