# Generated by Django 6.1.1 on 2026-10-02 18:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def RemoverQuantidadeDosProdutosPorPeso(Apps, SchemaEditor):
    ProdutoHistorico = Apps.get_model("produtos", "Produto")
    ProdutoHistorico.objects.filter(UnidadeVenda="quilograma").update(
        QuantidadeEstoque=None,
        EstoqueMinimo=None,
        Disponivel=True,
    )


def RestaurarQuantidadeDosProdutosPorPeso(Apps, SchemaEditor):
    ProdutoHistorico = Apps.get_model("produtos", "Produto")
    ProdutoHistorico.objects.filter(UnidadeVenda="quilograma").update(
        QuantidadeEstoque=Decimal("0.000"),
        EstoqueMinimo=Decimal("0.000"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='Disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='Fornecedor',
            field=models.CharField(default='Não informado', max_length=120),
        ),
        migrations.AddField(
            model_name='produto',
            name='Marca',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='produto',
            name='EstoqueMinimo',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='QuantidadeEstoque',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='UnidadeVenda',
            field=models.CharField(choices=[('unidade', 'Unidade'), ('quilograma', 'Quilograma'), ('metro', 'Metro'), ('valor_fixo', 'Preço fixo')], default='unidade', max_length=12),
        ),
        migrations.RunPython(
            RemoverQuantidadeDosProdutosPorPeso,
            RestaurarQuantidadeDosProdutosPorPeso,
        ),
    ]
