# Generated by Django 6.1.1 on 2026-10-02 19:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def PreencherPrecoCustoInicial(Apps, SchemaEditor):
    Produto = Apps.get_model("produtos", "Produto")
    Produto.objects.update(PrecoCusto=models.F("PrecoVenda"))


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_relacionar_produto_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='PrecoCusto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.RunPython(
            PreencherPrecoCustoInicial,
            migrations.RunPython.noop,
        ),
    ]
