# Generated by Django 6.1.1 on 2026-10-05 23:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def CriarLotesIniciais(Apps, SchemaEditor):
    Produto = Apps.get_model("produtos", "Produto")
    LoteEstoque = Apps.get_model("produtos", "LoteEstoque")

    Lotes = []

    for ProdutoExistente in Produto.objects.all().iterator():
        ControlaQuantidade = ProdutoExistente.UnidadeVenda != "quilograma"
        TemSaldo = (
            ProdutoExistente.QuantidadeEstoque is not None
            and ProdutoExistente.QuantidadeEstoque > 0
        )
        Lotes.append(
            LoteEstoque(
                Produto_id=ProdutoExistente.id,
                Fornecedor_id=ProdutoExistente.Fornecedor_id,
                QuantidadeInicial=ProdutoExistente.QuantidadeEstoque,
                QuantidadeDisponivel=ProdutoExistente.QuantidadeEstoque,
                PrecoCusto=ProdutoExistente.PrecoCusto,
                PrecoVenda=ProdutoExistente.PrecoVenda,
                Disponivel=ProdutoExistente.Disponivel,
                Ativo=(
                    ProdutoExistente.Ativo
                    and (not ControlaQuantidade or TemSaldo)
                ),
            )
        )

    LoteEstoque.objects.bulk_create(Lotes)


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
        ('produtos', '0004_produto_precocusto'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantidadeInicial', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('QuantidadeDisponivel', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('PrecoCusto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('PrecoVenda', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('Disponivel', models.BooleanField(default=True)),
                ('Ativo', models.BooleanField(default=True)),
                ('CriadoEm', models.DateTimeField(auto_now_add=True)),
                ('Fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LotesEstoque', to='fornecedor.fornecedor')),
                ('Produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LotesEstoque', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'lote de estoque',
                'verbose_name_plural': 'lotes de estoque',
                'ordering': ['CriadoEm', 'id'],
            },
        ),
        migrations.RunPython(
            CriarLotesIniciais,
            migrations.RunPython.noop,
        ),
    ]
